### PR TITLE
Fix test errors

### PR DESCRIPTION
**Pull request by sttk**
This pr fixes test errors and contains some modifications to keep up this module.

### CODE REVIEW

**Comment by sttk** [comment]
Sorry, I found a mistake. I moved `test/fixtures/node_modules` to `test/fixtures/cwd/node_modules`, because specifying `cwd = 'test/fixtures'` is not different from using default cwd when a loaded file path is `test/fixtures/*` (by [this](https://github.com/js-cli/js-rechoir/pull/35/files?diff=unified#diff-168726dbe96b3ce427e7fedce31bb0bcL25)).

**Comment by sttk** [comment]
I've modified `README.md`.

**Comment by phated** [comment]
@sttk it's funny you tackled this.  I have a local branch that has similar changes (though, I was upgrading the devDeps).

**Comment by sttk** [comment]
@phated What I really want to do is #36. Would you post your changes? Then I'll rebase #36 on it.

**Comment by sttk** [comment]
I'll close this pr because #36 is not needed for js-cli/js-liftoff#53.

**Pull request closed without merging**
